### ISSUE TITLE
memset(startv, 0, nsyms * sizeof*startv)   in function  interleave  has risk of buffer overflow 

### ISSUE THREAD

**Issue by zxxunkxzhx** [mischasan/aho-corasick#35]
should be
memset(startv, 0, sizeof*startv);
instead

**Comment by mischasan** [comment]
nsyms is the number of different byte values in the pattern text (i.e.
gteed no more than 256).

But thanks: looking at the code, I can see that the memset is totally
redundant, because initializing
    STATE startv[257][2] = { 0 };
or even just
    .... = {};
does the same as your memset.

On 09/02/2021, zxxunkxzhx <notifications@github.com> wrote:
> should be
> memset(startv, 0, sizeof*startv);
> instead
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mischasan/aho-corasick/issues/35


-- 
Engineers think equations approximate reality.
Physicists think reality approximates the equations.
Mathematicians never make the connection.

**Comment by zxxunkxzhx** [comment]
got it, thanks.

**Comment by zxxunkxzhx** [comment]
can changed into
STATE last_trans = 0, startv[257][2];
memset(startv, 0, (nsyms+1)*sizeof(*startv));

or can keep code unchanged

now close the ticket

**Comment by zxxunkxzhx** [comment]
closing
